{% set name = "synchronicity" %}
{% set version = "0.9.11" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/synchronicity-{{ version }}.tar.gz
  sha256: cb5dbbcb43d637e516ae50db05a776da51a705d1e1a9c0e301f6049afc3c2cae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - sigtools >=4.0.1
    - typing_extensions >=4.12.2

test:
  imports:
    - synchronicity
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/synchronicity/
  summary: Export blocking and async library versions from a single async implementation
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/modal-labs/synchronicity

extra:
  recipe-maintainers:
    - aksh-at
    - erikbern
    - freider
    - mwaskom
